export const FILLED = Symbol('▮')
export const CLEAR = Symbol('.')
export const CLEAR_BEFORE_REQUESTED = Symbol('[')
export const CLEAR_AFTER_REQUESTED = Symbol(']')
export const CLEAR_PADDING_REQUESTED = Symbol('-')
export const UNKNOWN = Symbol(' ')
